Repository fga-eps-mds/2021.1-PCTs-Frontend, pull requests merged in 2021-11, with the labels that each got.

#33 Release 3.0.1
  package.json
  src/routes/index.tsx
  static.json
  yarn.lock
Labels: PATCH

#34 Prevent click event propagation
  src/Components/SourceItem/index.tsx
Labels: bug, HOTFIX

#42 Release 3.1.1
  .env
  .github/workflows/ci_cd.yml
  .gitignore
  dev-env
  docker-compose.yml
  package.json
  src/Components/Carousel/index.tsx
  src/Components/Carousel/mockedPosts.ts
  src/Components/CarouselCard/index.tsx
  src/Components/DateFilterModal/index.tsx
  src/Components/ExecutionDetailItem/index.tsx
  src/Components/ExecutionDetailItem/styles.ts
  src/Components/ExecutionDetailsModal/index.tsx
  src/Components/Header/index.tsx
  src/Components/Header/styles.ts
  src/Components/KeywordItem/index.tsx
  src/Components/KeywordItem/styles.ts
  src/Components/KeywordModal/index.tsx
  src/Components/MonitoringCard/index.tsx
  src/Components/MonitoringCard/styles.ts
  src/Components/ProtectedRoute/index.tsx
  src/Components/ResultCard/index.tsx
  src/Components/ResultCard/styles.ts
  src/Components/SearchBar/styles.ts
  src/Components/SelectFilter/index.tsx
  src/Components/SourceItem/index.tsx
  src/Components/SourceItem/styles.ts
  src/Components/SourceModal/index.tsx
  src/Pages/AboutUs/index.tsx
  src/Pages/Admin/index.tsx
  src/Pages/Admin/styles.ts
  src/Pages/HomeScreen/index.tsx
  src/Pages/HomeScreen/styles.ts
  src/Pages/Keywords/index.tsx
  src/Pages/Keywords/styles.ts
  src/Pages/Login/index.tsx
  src/Pages/Login/styles.ts
  src/Pages/Monitoring/index.tsx
  src/Pages/Monitoring/styles.ts
  src/Pages/Results/index.tsx
  src/Pages/Results/styles.ts
  src/Pages/SignUp/index.tsx
  src/Pages/SignUp/styles.ts
  src/Pages/Sources/index.tsx
  src/Pages/Sources/styles.ts
  src/assets/images/PPGDSLogo.png
  src/assets/images/UnimontesLogo.png
  src/index.tsx
  src/routes/index.tsx
  src/services/api.ts
  src/services/apiCrawlers.ts
  src/services/apiDocuments.ts
  src/utils/userAuthentication.tsx
  yarn.lock
Labels: enhancement, MINOR, FEATURE, Frontend

#44 Release 3.1.1
  package.json
  public/index.html
  src/Components/Footer/index.tsx
  src/Components/Header/index.tsx
  src/Components/ResultCard/styles.ts
  src/Pages/HomeScreen/index.tsx
  src/Pages/Login/index.tsx
  src/Pages/Login/styles.ts
  src/Pages/Results/index.tsx
  src/assets/images/LogoPCT.png
Labels: PATCH, FEATURE, Frontend

#45 Hotfix - fix responsivity on login form
  src/Pages/Login/index.tsx
Labels: PATCH

#46 Hotfix - change date format to 24h
  src/Components/ExecutionDetailItem/index.tsx
  src/Components/KeywordItem/index.tsx
  src/Components/MonitoringCard/index.tsx
  src/Components/ResultCard/index.tsx
  src/Components/SourceItem/index.tsx
Labels: PATCH
